### ISSUE TITLE
fail to install second glitch_soc instance on the same server

### ISSUE THREAD

**Issue by lucyferu** [YunoHost-Apps/glitchsoc_ynh#152] opened 2023-09-10 19:53 UTC
### Describe the bug

cannot install glitch_soc a second time on my server

### Context

- Hardware: *VPS bought online *
- YunoHost version: 11.2.4
- I have access to my server: *Through SSH | through the webadmin *
- Using, or trying to install package version/branch: 2023.08.29~ynh1

### Steps to reproduce

   1. *have a first installation of glitch_soc on your server on a subdomain*
   2. *try to install a second one on a different subdomain*
   3. *an error will interrupt the installation*

### Expected behavior

*have two separated glitch_soc instances on my server.
i used to have them a few months back, meaning it used to work. something changed with one of the updates i guess.*

### Logs

just for continuity, i reported this issue also [on the forum](https://forum.yunohost.org/t/glich-soc-a-glitchy-but-lovable-microblogging-server/18905/13?u=unmy).
at the time there was an older version of the app, hence the problem is persisting.

full log from [yunopaste](https://paste.yunohost.org/raw/ekatoyuxix).

**Comment by Tagadda** [comment] 2023-12-24 21:46
I can't reproduce this issue.
@lucyferu, do you still encounter this issue nowadays ?

**Comment by OniriCorpe** [comment] 2024-02-15 20:42
poke @lucyferu

**Comment by lucyferu** [comment] 2024-02-16 08:56
Sorry for the late reply.
I honestly gave up on it after a while and installed GoToSocial instead.
If it helps, I can try again and share the results with you?

**Comment by Tagadda** [comment] 2024-02-16 09:40
If you will, sure!
I'm closing this issue for now but feel free to reopen it again with your result and logs :D

**Closed by Tagadda** 2024-02-16 09:40 UTC
